# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Awesome

on:
  issues:
    types:
      - opened
      - edited
      - reopened
      - labeled

jobs:
  update_library:
    runs-on: ubuntu-latest
    name: Convert awesome issues to data
    # only continue if issue has "awesome-workspace" label
    # require an `approved` label for moderation
    if: contains( github.event.issue.labels.*.name, 'awesome-workspace') && contains( github.event.issue.labels.*.name, 'approved')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.GOOGLEWORKSPACE_BOT_TOKEN }}
      - name: GitHub Issue to JSON
        uses: zachleat/github-issue-to-json-file@v3.0.14
        with:
          folder: "data/awesome"
          issue-template: "awesome.yml"
          hash-property-name: "github"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/awesome
          git commit -m "chore: adding data for #${{ env.IssueNumber }}"
          git push
      - name: Close issue
        uses: peter-evans/close-issue@v1
        with:
          issue-number: "${{ env.IssueNumber }}"
          comment: "Thank you! Your submission has been added!"
